package com.yx.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FILE_PERMISSION".
 */
public class FilePermission {

    private Long id;
    private Long uid;
    private String fileName;
    private Integer level;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FilePermission() {
    }

    public FilePermission(Long id) {
        this.id = id;
    }

    public FilePermission(Long id, Long uid, String fileName, Integer level) {
        this.id = id;
        this.uid = uid;
        this.fileName = fileName;
        this.level = level;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
