package com.yx.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCHOOL".
 */
public class School {

    private Long id;
    private long uid;
    private String category;
    private String title;
    private java.util.Date starttime;
    private java.util.Date endtime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public School() {
    }

    public School(Long id) {
        this.id = id;
    }

    public School(Long id, long uid, String category, String title, java.util.Date starttime, java.util.Date endtime) {
        this.id = id;
        this.uid = uid;
        this.category = category;
        this.title = title;
        this.starttime = starttime;
        this.endtime = endtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public java.util.Date getStarttime() {
        return starttime;
    }

    public void setStarttime(java.util.Date starttime) {
        this.starttime = starttime;
    }

    public java.util.Date getEndtime() {
        return endtime;
    }

    public void setEndtime(java.util.Date endtime) {
        this.endtime = endtime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
