package com.yx.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "VIRTUAL_USER".
 */
public class VirtualUser {

    private Long id;
    private long uid;
    private String username;
    private String portrait;
    private String signature;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public VirtualUser() {
    }

    public VirtualUser(Long id) {
        this.id = id;
    }

    public VirtualUser(Long id, long uid, String username, String portrait, String signature) {
        this.id = id;
        this.uid = uid;
        this.username = username;
        this.portrait = portrait;
        this.signature = signature;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
